name: CI - Build on Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libfreetype-dev \
            libgl-dev \
            libx11-dev \
            libxau-dev \
            zlib1g-dev \
            liblua5.4-dev \
            portaudio19-dev \
            libfftw3-dev \
            ffmpeg

      - name: Configure CMake
        run: cmake -S. -Bbuild -DAUDIOVIZ_TESTS=1

      - name: Build project
        run: cmake --build build -j$(nproc)

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: audioviz-build
          path: |
            build/libaudioviz/libaudioviz.*
            build/ttviz/ttviz
            build/luaviz/luaviz*
            build/test/*-test
            shaders/
